name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: macos-latest, r: 'release'}

    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})

    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library

    steps:
      - uses: actions/checkout@v4

      # Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      # Cache installed R packages
      - uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-ldtr
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      # Install only required R packages as binaries
      - name: Install R package dependencies
        run: Rscript -e 'install.packages(c("sf", "any::rcmdcheck"), dependencies = TRUE, type = "binary")'

      # Run R CMD check
      - name: Check
        run: Rscript -e 'rcmdcheck::rcmdcheck(
                            args = c("--no-manual", "--ignore-vignettes", "--no-build-vignettes"),
                            error_on = "warning",
                            check_dir = "check")'
